package com.denluoyia.douyue.manager.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.denluoyia.douyue.model.db.MyCollectionBean;
import com.denluoyia.douyue.model.db.NoteBean;

import com.denluoyia.douyue.manager.db.greendao.MyCollectionBeanDao;
import com.denluoyia.douyue.manager.db.greendao.NoteBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCollectionBeanDaoConfig;
    private final DaoConfig noteBeanDaoConfig;

    private final MyCollectionBeanDao myCollectionBeanDao;
    private final NoteBeanDao noteBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCollectionBeanDaoConfig = daoConfigMap.get(MyCollectionBeanDao.class).clone();
        myCollectionBeanDaoConfig.initIdentityScope(type);

        noteBeanDaoConfig = daoConfigMap.get(NoteBeanDao.class).clone();
        noteBeanDaoConfig.initIdentityScope(type);

        myCollectionBeanDao = new MyCollectionBeanDao(myCollectionBeanDaoConfig, this);
        noteBeanDao = new NoteBeanDao(noteBeanDaoConfig, this);

        registerDao(MyCollectionBean.class, myCollectionBeanDao);
        registerDao(NoteBean.class, noteBeanDao);
    }
    
    public void clear() {
        myCollectionBeanDaoConfig.clearIdentityScope();
        noteBeanDaoConfig.clearIdentityScope();
    }

    public MyCollectionBeanDao getMyCollectionBeanDao() {
        return myCollectionBeanDao;
    }

    public NoteBeanDao getNoteBeanDao() {
        return noteBeanDao;
    }

}
