package com.denluoyia.douyue.manager.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.denluoyia.douyue.model.db.NoteBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTE_BEAN".
*/
public class NoteBeanDao extends AbstractDao<NoteBean, Long> {

    public static final String TABLENAME = "NOTE_BEAN";

    /**
     * Properties of entity NoteBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Status = new Property(3, int.class, "status", false, "STATUS");
        public final static Property CreateTime = new Property(4, long.class, "createTime", false, "CREATE_TIME");
        public final static Property LastEditTime = new Property(5, long.class, "lastEditTime", false, "LAST_EDIT_TIME");
    }


    public NoteBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NoteBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"CONTENT\" TEXT NOT NULL ," + // 2: content
                "\"STATUS\" INTEGER NOT NULL ," + // 3: status
                "\"CREATE_TIME\" INTEGER NOT NULL ," + // 4: createTime
                "\"LAST_EDIT_TIME\" INTEGER NOT NULL );"); // 5: lastEditTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NoteBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindString(3, entity.getContent());
        stmt.bindLong(4, entity.getStatus());
        stmt.bindLong(5, entity.getCreateTime());
        stmt.bindLong(6, entity.getLastEditTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NoteBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
        stmt.bindString(3, entity.getContent());
        stmt.bindLong(4, entity.getStatus());
        stmt.bindLong(5, entity.getCreateTime());
        stmt.bindLong(6, entity.getLastEditTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NoteBean readEntity(Cursor cursor, int offset) {
        NoteBean entity = new NoteBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.getString(offset + 2), // content
            cursor.getInt(offset + 3), // status
            cursor.getLong(offset + 4), // createTime
            cursor.getLong(offset + 5) // lastEditTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NoteBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.getString(offset + 2));
        entity.setStatus(cursor.getInt(offset + 3));
        entity.setCreateTime(cursor.getLong(offset + 4));
        entity.setLastEditTime(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NoteBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NoteBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NoteBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
